import type { GptTargetCompanyRow } from "@/lib/api/gptTargetUniverse/service";

function buildSupplementaryContext(row: GptTargetCompanyRow): string | null {
  const lines: string[] = [];
  if (row.reason_summary?.trim()) {
    lines.push(`- Screening narrative (verify independently): ${row.reason_summary.trim()}`);
  }
  if (row.business_type?.trim()) {
    lines.push(`- Stated business-type label (verify independently): ${row.business_type.trim()}`);
  }
  if (row.operating_model?.trim()) {
    lines.push(`- Stated operating-model label (verify independently): ${row.operating_model.trim()}`);
  }
  if (lines.length === 0) return null;
  return ["## SUPPLEMENTARY CONTEXT (NON-FINANCIAL — VERIFY ALL)", "", ...lines, ""].join("\n");
}

/**
 * Plain-text prompt for pasting into ChatGPT Deep Research.
 */
export function buildChatgptDeepResearchPrompt(row: GptTargetCompanyRow): string {
  const companyName = row.company_name?.trim() || "Unknown";
  const orgnr = row.orgnr;
  const website = row.gpt_official_website_url?.trim() || "unknown";

  const internalFinancials = [
    "**Multi-year financial statements were not included in this handoff.**",
    "",
    "You MUST use browsing to obtain statutory accounts, annual reports, and/or reliable registry or aggregator data for this Swedish organization number, then treat that as your **internal financial anchor** for Steps 3 onward.",
    "",
    "Do not invent figures. If public data is thin, say so and proceed with explicit uncertainty.",
  ].join("\n");

  const supplementary = buildSupplementaryContext(row);

  return [
    "You are acting as a senior private equity / buy-side analyst.",
    "",
    "Your task is to perform a DEEP, evidence-based analysis of a single company using:",
    "1) Internal financial data (provided below)",
    "2) External research (you MUST use browsing to validate and expand)",
    "",
    "This is NOT a summary task. You are expected to think, challenge assumptions, and form an investment view.",
    "",
    "---",
    "",
    "## COMPANY INPUT",
    "",
    `Company: ${companyName}`,
    `Org nr: ${orgnr}`,
    `Website: ${website}`,
    "",
    "---",
    "",
    "## INTERNAL FINANCIAL DATA (CRITICAL SOURCE)",
    "",
    internalFinancials,
    "",
    "You MUST anchor your analysis in real financial data once obtained via browsing.",
    "Do NOT ignore inconsistencies between financials and narrative.",
    "",
    supplementary ? `${supplementary}` : "",
    "---",
    "",
    "## YOUR PROCESS (MANDATORY)",
    "",
    "Follow this exact workflow:",
    "",
    "### Step 1 — Identity Validation (FIRST PRIORITY)",
    "- Determine what the company ACTUALLY does",
    "- Use website + external sources",
    "- Resolve ambiguity:",
    "  - If unclear → list top 2–3 possible interpretations and assign probability",
    "",
    "DO NOT proceed with wrong assumptions.",
    "",
    "---",
    "",
    "### Step 2 — External Research (DEEP RESEARCH REQUIRED)",
    "",
    "You MUST:",
    "- Use browsing to find:",
    "  - company website content",
    "  - customer segments",
    "  - competitors",
    "  - industry context",
    "- Prioritize:",
    "  - primary sources (website)",
    "  - secondary validation (registries, articles, listings)",
    "",
    "Avoid generic industry descriptions.",
    "",
    "---",
    "",
    "### Step 3 — Financial Interpretation",
    "",
    "Using the financial data you sourced:",
    "",
    "- Revenue trend: explain WHY (not just what)",
    "- Margins: structural vs volatile?",
    "- Stability: predictable vs project-based?",
    "- Efficiency: any signals (e.g. scaling without margin expansion?)",
    "",
    "Identify:",
    "- anomalies",
    "- inflection points",
    "- contradictions vs business model",
    "",
    "---",
    "",
    "### Step 4 — Business Model Diagnosis",
    "",
    "Be explicit:",
    "",
    "- Revenue type:",
    "  (recurring / project / transactional / hybrid)",
    "",
    "- Scalability:",
    "  (low / medium / high — explain WHY)",
    "",
    "- Operational model:",
    "  (asset-heavy / labor-heavy / capital-light)",
    "",
    "- Dependency risks:",
    "  (customers / suppliers / geography)",
    "",
    "---",
    "",
    "### Step 5 — Market & Position",
    "",
    "- What niche are they REALLY in?",
    "- Is this:",
    "  - commodity",
    "  - specialized niche",
    "  - premium positioning",
    "",
    "- Market structure:",
    "  (fragmented vs consolidated)",
    "",
    "---",
    "",
    "### Step 6 — Synthesis (THIS IS THE CORE)",
    "",
    "Combine:",
    "- financial reality",
    "- business model",
    "- market position",
    "",
    "Answer:",
    "",
    "👉 What kind of company is this, fundamentally?",
    "",
    "Examples:",
    "- \"Local service operator with limited scalability\"",
    "- \"Niche industrial supplier with pricing power\"",
    "- \"Low-margin volume distributor\"",
    "- etc.",
    "",
    "Be precise.",
    "",
    "---",
    "",
    "### Step 7 — Strengths (ONLY REAL ONES)",
    "",
    "List 3–5 strengths:",
    "- MUST be supported by data or evidence",
    "- NO generic statements",
    "",
    "---",
    "",
    "### Step 8 — Risks (CRITICAL)",
    "",
    "List 3–5 risks:",
    "- structural (not surface-level)",
    "- linked to financials or model",
    "",
    "---",
    "",
    "### Step 9 — Investment View (DECISIVE)",
    "",
    "Answer clearly:",
    "",
    "- Is this investable? (Yes / No / Maybe)",
    "- For what type of investor?",
    "- What would need to change to make it attractive?",
    "",
    "---",
    "",
    "### Step 10 — Confidence & Unknowns",
    "",
    "- Confidence level (0–1)",
    "- What are the biggest unknowns?",
    "- Where could this analysis be wrong?",
    "",
    "---",
    "",
    "## OUTPUT STYLE",
    "",
    "- Be sharp, not long",
    "- No fluff, no buzzwords",
    "- Prioritize insight over completeness",
    "- Write like an investor memo, not a consultant report",
    "",
    "---",
    "",
    "## IMPORTANT RULES",
    "",
    "- DO NOT summarize the website",
    "- DO NOT repeat input data",
    "- DO NOT hallucinate — state uncertainty explicitly",
    "- ALWAYS tie conclusions to evidence",
    "",
    "---",
    "",
    "## GOAL",
    "",
    "This analysis will be used to:",
    "- identify acquisition targets",
    "- train internal screening logic",
    "- refine investment heuristics",
    "",
    "Think accordingly.",
  ]
    .filter((line) => line !== "")
    .join("\n");
}
